### ISSUE TITLE
New addition?

### ISSUE THREAD

**Issue by eduard626** [timzhang642/3D-Machine-Learning#25]
Hi,
Found this in CVPR 2018
PointGrid: A Deep Network for 3D Shape Understanding
http://openaccess.thecvf.com/content_cvpr_2018/papers/Le_PointGrid_A_Deep_CVPR_2018_paper.pdf
Code: https://github.com/47deg/pointgrid

Volumetric grid is widely used for 3D deep learning due to its regularity. However the use of relatively ower order local approximation functions such as piece-wise constant function (occupancy grid) or piece-wise linear function (distance field) to approximate 3D shape means that it needs a very high-resolution grid to represent finer geometry details, which could be memory and computationally  nefficient. In this work, we propose the PointGrid, a 3D convolutional network that incorporates a constant number of points within each grid cell thus allowing the network to learn higher order local approximation functions that could better represent the local geometry shape details. With experiments on popular shape recognition benchmarks, PointGrid demonstrates state-of-the-art performance over existing deep learning methods on both classification and segmentation

**Comment by timzhang642** [comment]
Thanks, it's now added! Although I think the code url should be this one: https://github.com/trucleduc/PointGrid
