### ISSUE TITLE
slack link not active

### ISSUE THREAD

**Issue by yd-yin** [timzhang642/3D-Machine-Learning#56]
"This invite link is no longer active."
Could you please update the link?

**Comment by timzhang642** [comment]
Just tried the link and it works for me. Could you double check it? Let me know if the issue still remains.

**Comment by ashwinimanoj** [comment]
It doesn't work for me either. Could you try from incognito and see if it works @timzhang642 ?

**Comment by labellson** [comment]
I have the same problem, the invitation link is not longer available

**Comment by timzhang642** [comment]
Just updated the link, should be working now.
