### ISSUE TITLE
How to visualise point cloud data like ModelNet40?

### ISSUE THREAD

**Issue by merazlab** [timzhang642/3D-Machine-Learning#66]

**Comment by chenbomath** [comment]
What is the format of the data? If it is off file or obj file, can use MeshLab to visualize it. And I checked the website for ModelNet40, seems that the format is .off. So I recommend you to use MeshLab, free to download for all os.

Best regards,
Chen Bo

**Comment by merazlab** [comment]
Thanks bob.
