### ISSUE TITLE
Adding useful tools

### ISSUE THREAD

**Issue by ialhashim** [timzhang642/3D-Machine-Learning#7]
I was thinking maybe include other intresting resources like this paper [UnrealCV](https://github.com/unrealcv/unrealcv). I am not sure where it fits. They also have a list of similar resources [synthetic-computer-vision](https://github.com/unrealcv/synthetic-computer-vision)

**Comment by timzhang642** [comment]
I've added UnrealCV under Datasets - 3D Scenes. It's a cool resource, thanks for sharing.
